name = "AutodiffAndOptimization"
uuid = "105ffcd2-060d-495b-a985-7b4e117e6040"
authors = ["GiggleLiu"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
